config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :member
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



	attr_accessor :email, :password, :password_confirmation, :remember_me, :username
	has_one :contact 
      
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController

	def new

		@member= Member.new
		@contact = Contact.new
	end

	def create

		@member = Member.new
		@member.username = params[:member][:username]
		@member.email = params[:member][:email]
		@member.password = params[:member][:password]
		@member.password_confirmation =params[:member][:password_confirmation]

		@contact = Contact.new
		@contact.mobile = params[:contact][:mobile]
		@contact.address = params[:contact][:address]
		@member.valid?
		if @member.errors.blank?

			@member.save
			@contact.member = @member
			@contact.save
			redirect_to dashboard_path
		else
			render :action => "new"
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
	
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/home/dashboard.html.erb
<p>hi welcome to Ruby community. you have successfully registered to your rails club account</p>
<%= link_to "Sign out", destroy_member_session_path, :method => :delete %>

app/views/home/index.html.erb
<% if member_signed_in? %>

<h3>you have succesfully signed in</h3>


<% else %>

<h1> welcom to rails community</h1>
<%= link_to "Sign In", new_member_session_path, :method => :get %>
<%= link_to "Sign up", new_member_registration_path, :method => :get %>


<% end %>
<%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>